This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./main2.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main2.acn....done (80 entries accepted, 0 rejected).
Sorting entries....done (513 comparisons).
Generating output file main2.acr....done (102 lines written, 0 warnings).
Output written in main2.acr.
Transcript written in main2.alg.
